// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLPEFed9RP5m-kxujGMP6B8WxfxdsYD8k',
    appId: '1:893803257995:web:5e0b19bcea95c5c05d348e',
    messagingSenderId: '893803257995',
    projectId: 'academyx-dcf09',
    authDomain: 'academyx-dcf09.firebaseapp.com',
    storageBucket: 'academyx-dcf09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_SiboDymZWUB20SlptBuzvCxi93X4Uz4',
    appId: '1:893803257995:android:372c0a6e3350bc495d348e',
    messagingSenderId: '893803257995',
    projectId: 'academyx-dcf09',
    storageBucket: 'academyx-dcf09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTULybmr7lR_Dzv7CXMnINu_sj8VMxC7s',
    appId: '1:893803257995:ios:ebb6e1b3f5e630985d348e',
    messagingSenderId: '893803257995',
    projectId: 'academyx-dcf09',
    storageBucket: 'academyx-dcf09.appspot.com',
    iosBundleId: 'com.example.academyx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTULybmr7lR_Dzv7CXMnINu_sj8VMxC7s',
    appId: '1:893803257995:ios:ebb6e1b3f5e630985d348e',
    messagingSenderId: '893803257995',
    projectId: 'academyx-dcf09',
    storageBucket: 'academyx-dcf09.appspot.com',
    iosBundleId: 'com.example.academyx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLPEFed9RP5m-kxujGMP6B8WxfxdsYD8k',
    appId: '1:893803257995:web:54a7d1d4ca6566db5d348e',
    messagingSenderId: '893803257995',
    projectId: 'academyx-dcf09',
    authDomain: 'academyx-dcf09.firebaseapp.com',
    storageBucket: 'academyx-dcf09.appspot.com',
  );
}
